### ISSUE TITLE
[iOS] [Navigation] Page won't render after navigating to route with multiple views

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno.toolkit.ui#346]
## Current behavior

Page doesn't load on going back after navigating with a route with multiple views.

## Expected behavior

When going back page should load.

## How to reproduce it (as minimally and precisely as possible)

-Navigate to second page
-Go back

Notice how first page didn't render

[MyAppTest2.zip](https://github.com/unoplatform/uno.extensions/files/9666778/MyAppTest2.zip)

## Environment

Nuget Package: Uno.Extensions.Navigation

Package Version(s): 2.2.0

Affected platform(s): iOS

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [X] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
Looks to also be an issue in Uno. The app is working when commenting out the ToolkResources init because the NativeFramePresenter isn't being used by default by Uno. If you were to add `FeatureConfiguration.Style.ConfigureNativeFrameNavigation();` to the App.xaml.cs ctor then it will also fail, regardless of Toolkit being included or not. Still trying to track down why this isn't working in the NativeFramePresenter logic though.

cc @nickrandolph

**Comment by kazo0** [comment]
Ok I see the issue, Frame has specific logic to instantiate the `Page` that will be the `PageStackEntry`'s Instance [here](https://github.com/unoplatform/uno/blob/5ced0586db066463250cf1cda47c5d9c77f5648b/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs#L348-L358). Problem is we are creating new PageStackEntries in the code-behind of these xaml pages here and NativeFramePresenter is working off of the assumption that the BackStack will contain PageStackEntries that already have their [Instance property](https://github.com/unoplatform/uno/blob/5ced0586db066463250cf1cda47c5d9c77f5648b/src/Uno.UI/UI/Xaml/Navigation/PageStackEntry.cs#L48) set.

Problem is that inside of Frame, the assignment of the PageStackEntry's Instance only occurs at the time of navigation. By that time, we should already have the up-to-date list that is matching the UIViewControllers to the Frame's BackStack. The Uno NativeFramePresenter is failing from a null-ref [here](https://github.com/unoplatform/uno/blob/5ced0586db066463250cf1cda47c5d9c77f5648b/src/Uno.UI/Controls/NativeFramePresenter.iOS.cs#L369) and the Toolkit NativeFramePresenter is creating a UIViewControllew but with a null View, [here](https://github.com/unoplatform/uno.toolkit.ui/blob/655516a2f63ddc15cb7d1114c876a2db861e09df/src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs#L409-L411).

**Comment by kazo0** [comment]
Ok to recap

Scenario is: you are trying to deep-link to BlankPage2. So you Frame.Navigate to BlankPage2 and then you insert into the backstack the pages that should exist "behind" BlankPage2:


```csharp
this.Frame.Navigate(typeof(BlankPage2));
this.Frame.BackStack.Clear();
this.Frame.BackStack.Add(new PageStackEntry(typeof(MainPage), null, null));
this.Frame.BackStack.Add(new PageStackEntry(typeof(BlankPage1), null, null));
```

The issue with this is that, at this point, we have `PageStackEntry`s that are not actually holding instances of `MainPage` or `BlankPage1`. So when we force the native ViewController back stack to align with the Frame's BackStack, we get PageViewControllers that have a View of null, because of [this logic](https://github.com/unoplatform/uno.toolkit.ui/blob/11274f612daf84a3a4913d7ed5e5cb1f1532b97a/src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs#L404-L412):


```csharp
var viewControllers = _frame?.BackStack
        .Concat(FrameNavigationHelper.GetCurrentEntry(_frame))
        .Where(entry => entry != null)
        .Distinct()
        .OfType<PageStackEntry>()
        .Select(entry => FrameNavigationHelper.GetInstance(entry) is { } instance
                ? instance.FindViewController() ?? new PageViewController(instance)
                : new PageViewController(null))
        .ToArray() ?? Array.Empty<PageViewController>();
```

The Frame does create the instance for the specific Page and includes it in the event args for its Navigated event. So we can find that instance in the NativeFramePresenter [here](https://github.com/unoplatform/uno.toolkit.ui/blob/11274f612daf84a3a4913d7ed5e5cb1f1532b97a/src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs#L229) and maybe quickly find the "empty" ViewController in the back stack and set it's View to this instance. But this won't help for situations where a navigation occurs natively, such as a back swipe, and the Frame navigation isn't invoked.

I'm guessing our only option is to instantiate instances of the Page within the [OnFrameBackStackChanged](https://github.com/unoplatform/uno.toolkit.ui/blob/11274f612daf84a3a4913d7ed5e5cb1f1532b97a/src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs#L326). I'd like to keep that responsibility in the Uno Frame and not deal with creating page instances and caching within the NativeFramePresenter. So maybe we can poke some sort of hole through using the [FrameNavigationHelper](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Helpers/FrameNavigationHelper.cs) that could call Frame's[ CreatePageInstance[Cached]](https://github.com/unoplatform/uno/blob/89cf24a9895329f96bcb3fe8f16cedf0e785d786/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs#L435-L437)?
