### ISSUE TITLE
Broken Links and Layout Broken link target

### ISSUE THREAD

**Issue by ghost** [unoplatform/uno.toolkit.ui#456]
## On which page?

https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls-styles.html 

## What's wrong?

Clicking in some links like: TabBarItem, will open a broken layout page:

![image](https://user-images.githubusercontent.com/100223422/214541247-84ed4d77-12ab-419d-ae21-a7df08f8c414.png)

## Any feedback?

As I could see, we have 2 issues in one: 

1. Links which are broken
2. Error page with broken layout

**Comment by kazo0** [comment]
Good catch! Will fix :)

**Comment by Xiaoy312** [comment]
Just for context, this is unrelated to #11109 (the linked PR wont fix this).
The problem here stems from how docfx parsed the relative file link:
```
markdown source: [`DrawerControl`](controls\DrawerControl.md)
generated html: <a href="controls%5CDrawerControl.md"><code>DrawerControl</code></a>
	^ 1. directory-separator `\` is url-encoded as %5C
    ^ 2. as `controls%5CDrawerControl.md` is a deadlink, the `.md` extension didnt get re-formatted to `.html`
```

based on docfx doc: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#link-to-a-file-using-relative-path
they seems to favor forward-slash, so that could be one option

**Comment by Xiaoy312** [comment]
of note: 
we still need to update the [snapshot reference in uno](https://github.com/unoplatform/uno/blob/master/doc/import_external_docs.ps1#L12) 
and then wait it to be published
