### ISSUE TITLE
[Material][Cupertino] Add samples for Top/Bottom TabBar / SegmentedControl / SlidingSegmentedControl

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.toolkit.ui#55]
## What would you like to be added:

[Material][Cupertino] Add samples for Top/Bottom TabBar / SegmentedControl / SlidingSegmentedControl

- Full gestures
- Being able to swipe
- All the animations when you're switching between selected item

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] MacOS
- [X] Skia
- [X] Windows

## More info:
**_Previous related draft PRs_**
- [feat: Sliding Segmented Control by duke7553 · Pull Request #610 · unoplatform/Uno.Themes (github.com)](https://github.com/unoplatform/Uno.Themes/pull/610)
- [feat: TabBar themes for Material and Cupertino by duke7553 · Pull Request #609 · unoplatform/Uno.Themes (github.com)](https://github.com/unoplatform/Uno.Themes/pull/609)

**Comment by agneszitte-nventive** [comment]
@kazo0 what should be the plan at this point for this issue?

**Comment by lukeblevins** [comment]
@agneszitte @kazo0 I noticed we're still in need of a plan for this issue. It appears we actually have [samples](https://github.com/search?q=repo%3Aunoplatform%2Funo.toolkit.ui%20path%3A%2F%5Esamples%5C%2FUno%5C.Toolkit%5C.Samples%5C%2FUno%5C.Toolkit%5C.Samples%5C.Shared%5C%2FContent%5C%2FControls%5C%2F%2F%20segmented&type=code) and published [docs](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/TabBarAndTabBarItem.html#tabbaritem-style) for `TabBar` and the `*SegmentedItemStyle` styles. 

Since those have been completed, I'll close this issue now. Please do reopen it if I missed something important. Otherwise, I assume we'd want to converge in some way with the [work](https://learn.microsoft.com/dotnet/communitytoolkit/windows/segmented/segmented) that is now part of WCT. If there's a need for doc updates during this cycle to communicate those changes, feel free to ping me.
