### ISSUE TITLE
Exception in AppBarButton when it is inside a NavigationBar in Android

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno.toolkit.ui#623]
### Current behavior

The AppBarButton works correctly in WinUI but:
	- Does not support SVG images in Wasm and Android.
	- When it is included in a NavigationBar it raises exception if the content is different of a BitmapImage in Android platform.

### Expected behavior

The AppBarButton supports all functionality on all platforms.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project and compile it. 
Execute the Android project and the NavigationBar fails to load because the AppBarButton image load throws an exception, if all the AppBarButton are commented except the one containing the BitmapImage it loads correctly.

Code that reproduces the error in this file:
[UnoAppBarButtonAndroid.zip](https://github.com/unoplatform/uno/files/11850172/UnoAppBarButtonAndroid.zip)

### Workaround

No workaround.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.9.20

### Affected platforms

WebAssembly, Android

### IDE

Visual Studio 2022

### IDE version

17.6.3

**Comment by kazo0** [comment]
@Suriman Looking into this now, I am able to see the FontIcons on WASM, is there another issue on WASM that you are experiencing?
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/053c2ad8-c9ff-4436-9f7a-9380c70fbfce)

Also, I have updated the package versions used in the sample app to the latest dev bits and the NavigationBar will now render, although the AppBarButtons that are not using a `BitmapIcon` will not display as this is still a limitation of the native bar being used on Android and iOS:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/f46ca4a9-d9a0-44ab-9eaf-28862314e2c8)


Attached is the up-to-date repro app
[AddInfo.zip](https://github.com/unoplatform/uno.toolkit.ui/files/11872420/AddInfo.zip)

**Comment by ADD-Eugenio-Lopez** [comment]
Yes, we know the limitation of the documentation that on Android it only works with BitmapImage, that's why we have commented it with Sasha and the issue has been opened as feature enhancement.

We have updated the package versions used in the sample app to the latest dev bits.
In WinUI we can see all the image sources:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/50919329/9f1d30bd-5517-4834-a138-15636d88777e)

In Wasm we can see all the image sources except the Svg image, but the ImageIcon with a Svg can be loaded correctly outside an AppBarButton:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/50919329/00752bfb-c635-407e-a8d7-68668592a381)

In Android we can see only the BitmapIcon, and now the exceptions are no longer thrown in the loading of images even if they are not loaded, note that content is also not loaded with the TextBlock in the NavigationBar:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/50919329/f438d56f-63e9-4211-9cd1-7e3453da0a4b)

**Comment by kazo0** [comment]
Should be fixed by https://github.com/unoplatform/uno.toolkit.ui/pull/622

**Comment by ADD-Eugenio-Lopez** [comment]
Although the title of the issue indicates that an exception occurs, that was corrected in 
  [#622](https://github.com/unoplatform/uno.toolkit.ui/pull/622), in the description of the issue we also indicate that we need to support all the IconElements that are being solved in the [#631](https://github.com/unoplatform/uno.toolkit.ui/pull/631), so we believe that this issue should not be closed until the [#631](https://github.com/unoplatform/uno.toolkit.ui/pull/631).
